In [1]:
import array as arr

In [2]:
a=arr.array('i',[1,2,3])
b=arr.array('d',[4.5,5.0,6.2,7.8])
c=arr.array('u',['a','b','c','d'])

In [9]:
print(a)
print(b)
print(c)

array('i', [1, 2, 3])
array('d', [4.5, 5.0, 6.2, 7.8])
array('u', 'abcd')


In [11]:
#finding the typecode of array
print(a.typecode)
print(b.typecode)
print(c.typecode)

i
d
u


In [12]:
#length of array
print(len(a))
print(len(b))
print(len(c))

3
4
4


In [13]:
#printing elements of array
for i in range(len(a)):
    print(a[i])

1
2
3


In [15]:
for i in range(len(c)):
    print(c[i],end="-")

a-b-c-d-

In [31]:
#indexing - accessing elements using index values
new_array=arr.array('i',[1,8,3,25,5,7,23,18,9])
print(new_array[5])

7


In [32]:
#adding elements
new_array.append(10)
print(new_array)

array('i', [1, 8, 3, 25, 5, 7, 23, 18, 9, 10])


In [33]:
new_array.insert(3,15)
print(new_array)

array('i', [1, 8, 3, 15, 25, 5, 7, 23, 18, 9, 10])


In [34]:
#updating the values
new_array[0]=100
print(new_array)

array('i', [100, 8, 3, 15, 25, 5, 7, 23, 18, 9, 10])


In [35]:
#Deleting the values
new_array.pop()
print(new_array)

array('i', [100, 8, 3, 15, 25, 5, 7, 23, 18, 9])


In [36]:
new_array.pop(2)
print(new_array)

array('i', [100, 8, 15, 25, 5, 7, 23, 18, 9])


In [37]:
new_array.remove(18)
print(new_array)

array('i', [100, 8, 15, 25, 5, 7, 23, 9])


In [38]:
#slicing
print(new_array[1:5])

array('i', [8, 15, 25, 5])


In [40]:
print(new_array[3:-3])

array('i', [25, 5])


In [41]:
print(new_array[::-1])

array('i', [9, 23, 7, 5, 25, 15, 8, 100])


In [44]:
# Iterate from the end to the beginning of the array
for i in range(-1, -len(new_array) - 1, -1):
    print(i,new_array[i])

-1 9
-2 23
-3 7
-4 5
-5 25
-6 15
-7 8
-8 100


In [48]:
print(new_array)

array('i', [100, 8, 15, 25, 5, 7, 23, 9])


In [50]:
for i in range(0,len(new_array)):
    print(i,'->',new_array[i])

0 -> 100
1 -> 8
2 -> 15
3 -> 25
4 -> 5
5 -> 7
6 -> 23
7 -> 9


In [45]:
#finding the index
print(new_array.index(5))

4


In [47]:
element=25
print(new_array.index(element),element)

3 25


In [53]:
#sorting
sorted=new_array.tolist()
sorted.sort()
print(sorted)

[5, 7, 8, 9, 15, 23, 25, 100]


In [54]:
sorted.sort(reverse=True)
print(sorted)

[100, 25, 23, 15, 9, 8, 7, 5]


**NUMPY ARRAYS**

In [55]:
import numpy as np

In [56]:
array1=np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [61]:
#creating an matrix with zeros
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [63]:
#creating an matrix with ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
#creating an matrix with constant values
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [66]:
#creating an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
#1d,2d,3d numpy arrays
zerod=np.array(1)
print(zerod)



1


In [68]:
#1d array
oned=np.array([1,2,3,4,5])
print(oned)

[1 2 3 4 5]


In [69]:
#2d array
twod=np.array([
    [1,2,3],
     [4,5,6]
    ])
print(twod)

[[1 2 3]
 [4 5 6]]


In [70]:
#3d array
threed=np.array([
    [
        [1,2,3],
 [4,5,6]
                  ],[
                      [7,8,9],[10,11,12]
                      ]
    ])
print(threed)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [71]:
#multi dimensional array
multi=np.array([1,2,3,4],ndmin=5)
print(multi)

[[[[[1 2 3 4]]]]]


In [72]:
multi.ndim

5

In [80]:
#CRUD operations on Numpy Arrays
#reading from a numpy array
sample_array = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0,len(sample_array)):
  print(sample_array[i], end="")
print("\n")
#updating elements in a numpy array, we make use of indexing here.
sample_array[9] = 100
print(sample_array)
print("\n")
#deleting elements in a numpy array
sample_array = np.delete(sample_array, 9)
print(sample_array)

12345678910

[  1   2   3   4   5   6   7   8   9 100]


[1 2 3 4 5 6 7 8 9]


In [81]:
#searching elements in a numpy array
y =list(range(0,20000,3))
sample_search_array = np.array(y)
#searching the element 15000
res = np.where(sample_search_array==15000)
print(res)
#checking if the returning index is true
print(sample_search_array[5000])

(array([5000]),)
15000


In [83]:
#sorting elements in a numpy array
sample_sort_array = np.array([1,4,9,2,3,8,7,6])
 #sorting the numpy array using sort()
z =np.sort(sample_sort_array)
print(z)

[1 2 3 4 6 7 8 9]
